const List<String> spaceFacts = [
  "Jupiter is so big that all the other planets in the Solar System could fit inside it.",
  "A day on Venus is longer than a year on Venus.",
  "Saturn could float in water because it’s mostly gas and less dense than water.",
  "On Mars, sunsets appear blue because of how its atmosphere scatters sunlight.",
  "Neptune’s winds are the fastest in the Solar System — over 2,100 km/h.",
  "Uranus spins on its side — its axis is tilted 98 degrees.",
  "Stars don’t twinkle in space; they only twinkle when viewed through Earth’s atmosphere.",
  "The Sun makes up 99.8% of the Solar System’s mass.",
  "Our Sun is actually considered a normal star — it’s not especially big or small.",
  "Betelgeuse (a star in Orion) is so big that if it were placed in our Solar System, it would engulf Jupiter.",
  "Without the Moon, Earth’s tilt would wobble wildly — making life unstable.",
  "The Moon is moving away from Earth by about 3.8 cm every year.",
  "Earth’s atmosphere leaks into space; about 90 tons escape every day.",
  "One day, Earth’s rotation will slow so much that a day will be 47 hours long.",
  "Earth is hit by over 100 tons of space dust every day.",
  "The footprints on the Moon will last millions of years because there’s no wind or water.",
  "If Earth’s core cooled completely, we’d lose our magnetic field and solar radiation would fry us.",
  "Black holes can spaghettify anything — stretching it thin like noodles.",
  "Some black holes are billions of times more massive than the Sun.",
  "There might be rogue black holes drifting invisibly through the Milky Way.",
  "Time slows down near a black hole — one hour there could equal thousands of years far away.",
  "If you fell into a black hole, you’d never see yourself reach the center.",
  "Our Milky Way has a supermassive black hole at its center called Sagittarius A*.",
  "Black holes can collide and merge, shaking space-time itself.",
  "Some scientists believe primordial black holes formed right after the Big Bang.",
  "Astronauts grow about 2 inches taller in space because the spine stretches.",
  "Space smells like burned steak or welding fumes, according to astronauts.",
  "In space, metals can fuse together without heat — cold welding.",
  "On Venus, it rains acid — but drops evaporate before reaching the surface.",
  "If two pieces of the same metal touch in space, they can stick permanently.",
  "In zero gravity, tears don’t fall — they float on your face.",
  "Saturn’s moon Titan has lakes of liquid methane and ethane.",
  "On Mercury, a day lasts 1,408 Earth hours.",
  "There are more trees on Earth than stars in the Milky Way.",
  "There are more stars in the universe than grains of sand on all Earth’s beaches.",
  "The Milky Way will collide with the Andromeda Galaxy in about 4 billion years.",
  "The largest known galaxy, IC 1101, is 50 times bigger than the Milky Way.",
  "Some galaxies shoot out jets of plasma thousands of light-years long.",
  "Light from the Sun takes about 8 minutes to reach Earth.",
  "If the Sun were a white blood cell, the Milky Way would be the size of the USA.",
  "Most of the universe is made of dark matter and dark energy — we can’t see them.",
  "The observable universe is about 93 billion light-years across.",
  "Looking into space means looking back in time.",
  "The Boötes Void is a giant empty space, 330 million light-years wide.",
  "Some galaxies are so far away their light started traveling before Earth existed.",
  "A neutron star is so dense that a teaspoon weighs 4 billion tons.",
  "Space radiation can damage DNA and increase cancer risk.",
  "Without a suit, you’d pass out in 15 seconds in space.",
  "Asteroids wiped out the dinosaurs.",
  "Gamma-ray bursts could destroy Earth’s atmosphere if one hit nearby.",
  "It may rain diamonds on Neptune and Uranus.",
  "Olympus Mons on Mars is the largest volcano — 3x Mount Everest.",
  "Pulsars are neutron stars that send out beams like cosmic lighthouses.",
  "The Sun will expand into a red giant and swallow Earth someday.",
  "If Earth were 5% closer to the Sun, it would be too hot for liquid water.",
  "If Earth were 5% farther, it would be frozen solid.",
  "There may be more universes beyond ours — multiverse theory.",
  "Some exoplanets orbit two or even three stars.",
  "The universe is still expanding — galaxies rush away from us.",
  "Every atom in your body was made inside a star — you’re stardust."
];